require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rails
  - rubocop-rake

AllCops:
  NewCops: enable

Rails/SkipsModelValidations:
  Exclude:
    - '**/test/**/*'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/test/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Max: 300

Metrics/ModuleLength:
  Enabled: true
  Max: 300

Metrics/MethodLength:
  Enabled: true
  Max: 25

Lint/NestedMethodDefinition:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false
