require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: true
  EnforcedStyle: inline

Style/DoubleNegation:
  Enabled: false

Layout/LineLength:
  Max: 120

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false
