---
language: ruby
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
  # - 3.0.0
gemfile:
  - gemfiles/activerecord-5-2-stable
  - gemfiles/activerecord-6-0-stable
  - gemfiles/activerecord-6-1-stable
  - gemfiles/activerecord-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile-edge
    - gemfile: activerecord-6-0-stable
    - gemfile: activerecord-5-2-stable
before_install: gem install bundler -v 2.2.3 && bundle install
script: bundle exec rake
notifications:
  email: false
...
