name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [3.0]
        gemfile: [rails-6-1]
        experimental: [false]
        include:
          - gemfile: rails-edge
            ruby-version: 3.0
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.64.1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tasks
      run: |
        gem install bundler
        bundle install
        bundle exec rake
        BUNDLE_GEMFILE=../Gemfile bin/activerecord-test
